apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: bigtable-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bigtable-operator
  template:
    metadata:
      labels:
        app: bigtable-operator
    spec:
      containers:
      - env:
        - name: WORKER_IMAGE
          value: us-central1-docker.pkg.dev/sbhattarai-test101/bigtable-utils/bigtable-worker:latest
        - name: JAVA_WORKER_IMAGE
          value: us-central1-docker.pkg.dev/sbhattarai-test101/bigtable-utils/java-worker:latest
        - name: VALIDATION_WORKER_IMAGE
          value: us-central1-docker.pkg.dev/sbhattarai-test101/bigtable-utils/bigtable-validator:latest
        image: us-central1-docker.pkg.dev/sbhattarai-test101/bigtable-utils/crd-operator:latest
        imagePullPolicy: Always
        name: operator
      serviceAccountName: bigtable-worker-sa
