apiVersion: java.sushanb.com/v1
kind: JavaWorkload
metadata:
  name: test-single-channel-us-east1-java
spec:
  projectID: "autonomous-mote-782"
  instanceID: "test-sushanb"
  region: "asia-east1"
  tableID: "test"  # <--- Make sure this table exists!

  # 2. Scale
  replicas: 1

  # 3. Java Specific Tuning (Optional)
  jvmArgs: "-Xmx1536m -Xms1536m"
  appArgs: "--debug" # Passed as args to your main()
  serviceAccountName: "java-worker-sa"
  env:
    - name: BIGTABLE_HOST
      value: "google-c2p:///bigtable.googleapis.com"
    - name: SINGLE_CHANNEL_IN_FLIGHT
      value: "1"
    - name: APP_PROFILE
      value: "isolated"
    - name: PROJECT_ID
      value: "autonomous-mote-782"
    - name: INSTANCE_ID
      value: "neilwells-test"