apiVersion: bigtable.sushanb.com/v1
kind: BigtableWorkload
metadata:
  name: load-us-east7-jetstream
spec:
  projectID: "autonomous-mote-782"
  instanceID: "sushanb-jetstream"
  region: "us-east7"
  replicas: 2
  env:
    - name: CBT_ENV_VAR
      value: "prod"
    - name: CBT_ENABLE_DEBUG
      value: "true"
    - name: READ_QPS
      value: "500"
    - name: WRITE_QPS
      value: "500"
  serviceAccountName: "bigtable-worker-sa"
