apiVersion: bigtable.sushanb.com/v1
kind: BigtableWorkload
metadata:
  name: test-load-east4-go-worker-sushanb
spec:
  projectID: "autonomous-mote-782"
  instanceID: "test-sushanb"
  region: "us-east4"
  replicas: 1
  env:
    - name: CBT_ENABLE_DIRECTPATH
      value: "true"
    - name: CBT_BIGTABLE_CONN_POOL
      value: "true"
    - name: CBT_ENABLE_DEBUG
      value: "true"
    - name: CBT_ENV_VAR
      value: "test"
    - name: TARGET_QPS
      value: "1"
    - name: APP_PROFILE
      value: "default"
  serviceAccountName: "bigtable-worker-sa"
