apiVersion: bigtable.sushanb.com/v1
kind: BigtableWorkload
metadata:
  name: load-europe-west1-cache
spec:
  projectID: "autonomous-mote-782"
  instanceID: "sushanb-noncache"
  region: "europe-west1"
  replicas: 2
  env:
    - name: CBT_ENV_VAR
      value: "prod"
    - name: CBT_ENABLE_DEBUG
      value: "true"
    - name: READ_QPS
      value: "1500"
    - name: WRITE_QPS
      value: "150"
  serviceAccountName: "bigtable-worker-sa"
